name: Continuous Integration
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '.github/**'
      - '.gitgnore'
  pull_request:
    branches:
      - main
permissions:
  contents: read

env:
  GOTELEMETRY: off
  #CGO_ENABLED: 0

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          #go-version-file: 'go.mod'
          check-latest: true
      - name: Setup Test Keychain
        if: runner.os == 'macOS'
        run: |
          security create-keychain -p test-password aws-vault-test.keychain
          
          security default-keychain -s aws-vault-test.keychain
          
          security unlock-keychain -p test-password aws-vault-test.keychain
          
          security set-keychain-settings -t 3600 -u aws-vault-test.keychain
          
          security list-keychains -d user -s aws-vault-test.keychain $(security list-keychains -d user | sed s/\"//g)
      - name: Run tests
        run: make test #go test -race ./...
      - name: Cleanup Test Keychain
        if: runner.os == 'macOS' && always()
        run: |
          security delete-keychain aws-vault-test.keychain || true
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          #go-version-file: 'go.mod'
          check-latest: true
      - name: Lint
        run: make vet
      #- name: golangci-lint
      #  uses: golangci/golangci-lint-action@v8
      #  with:
      #    version: v2.1
